services:
  server-php-aev1:
    container_name: servidor_php_aev1
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ../:/www/html
    stdin_open: true
    links:
      - mariadb-server-aev1
    ports:
      - "8010:8010"
  mariadb-server-aev1:
    container_name: servidor_db_aev1
    image: mariadb
    ports:
      - "3310:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../.db_mysql/:/var/lib/mysql